version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
    commit-message:
      prefix: "chore(deps):"
    reviewers:
      - "leeadrian841"
    groups:
      react:
        patterns:
          - "react"
          - "react-dom"
          - "react-bootstrap"
          - "react-router-dom"
      vite:
        patterns:
          - "vite"
          - "@vitejs/*"
      bootstrap:
        patterns:
          - "bootstrap"
